# Generated by Django 5.1.7 on 2025-04-28 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Implant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implant_id', models.CharField(max_length=100, unique=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('results', models.TextField(blank=True, null=True)),
                ('implant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='c2.implant')),
            ],
        ),
    ]
